### ISSUE TITLE
Outdated WalletLink Code --> Needs to be updated to Coinbase Wallet SDK

### ISSUE THREAD

**Issue by TrevvvD** [akropolisio/web3-wallets-kit#46]
Hi,

I work on the DevRel team at Coinbase and am submitting this issue to inform you that the WalletLink SDK has been deprecated in favor of our new [Coinbase Wallet SDK](https://github.com/coinbase/coinbase-wallet-sdk). You can find more on that and how to upgrade to the latest version [here](https://docs.cloud.coinbase.com/wallet-sdk/docs/welcome).

Please let me know if you have any questions!

Thanks,
Trevor

**Comment by in19farkt** [comment]
We have added a new [@web3-wallets-kit/coinbase-connector](https://www.npmjs.com/package/@web3-wallets-kit/coinbase-connector) and deprecated the [@web3-wallets-kit/wallet-link-connector](https://www.npmjs.com/package/@web3-wallets-kit/wallet-link-connector) package in npm. @TrevvvD Thanks for the issue!
